# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saprmax2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1426, 825)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scroll_point = QtWidgets.QScrollArea(self.frame)
        self.scroll_point.setGeometry(QtCore.QRect(20, 50, 161, 231))
        self.scroll_point.setWidgetResizable(True)
        self.scroll_point.setObjectName("scroll_point")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 159, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_X = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_X)
        self.lineEdit_Y = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Y)
        self.label_X = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_X.setObjectName("label_X")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_X)
        self.label_Y = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Y.setObjectName("label_Y")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Y)
        self.scroll_point.setWidget(self.scrollAreaWidgetContents)
        self.btn_add_point = QtWidgets.QPushButton(self.frame)
        self.btn_add_point.setGeometry(QtCore.QRect(20, 290, 93, 28))
        self.btn_add_point.setObjectName("btn_add_point")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(20, 330, 781, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_render = QtWidgets.QPushButton(self.frame)
        self.pushButton_render.setGeometry(QtCore.QRect(810, 700, 141, 28))
        self.pushButton_render.setObjectName("pushButton_render")
        self.pushButton_graph_prod = QtWidgets.QPushButton(self.frame)
        self.pushButton_graph_prod.setGeometry(QtCore.QRect(810, 660, 141, 28))
        self.pushButton_graph_prod.setObjectName("pushButton_graph_prod")
        self.pushButton_graph_norm = QtWidgets.QPushButton(self.frame)
        self.pushButton_graph_norm.setGeometry(QtCore.QRect(810, 620, 141, 28))
        self.pushButton_graph_norm.setObjectName("pushButton_graph_norm")
        self.pushButton_graph_peremesh = QtWidgets.QPushButton(self.frame)
        self.pushButton_graph_peremesh.setGeometry(QtCore.QRect(810, 580, 141, 28))
        self.pushButton_graph_peremesh.setObjectName("pushButton_graph_peremesh")
        self.pushButton_table_peremesh = QtWidgets.QPushButton(self.frame)
        self.pushButton_table_peremesh.setGeometry(QtCore.QRect(810, 460, 141, 28))
        self.pushButton_table_peremesh.setObjectName("pushButton_table_peremesh")
        self.pushButton_table_prod = QtWidgets.QPushButton(self.frame)
        self.pushButton_table_prod.setGeometry(QtCore.QRect(810, 540, 141, 28))
        self.pushButton_table_prod.setObjectName("pushButton_table_prod")
        self.pushButton_table_norm = QtWidgets.QPushButton(self.frame)
        self.pushButton_table_norm.setGeometry(QtCore.QRect(810, 500, 141, 28))
        self.pushButton_table_norm.setObjectName("pushButton_table_norm")
        self.btn_add_kernel = QtWidgets.QPushButton(self.frame)
        self.btn_add_kernel.setGeometry(QtCore.QRect(180, 290, 93, 28))
        self.btn_add_kernel.setObjectName("btn_add_kernel")
        self.btn_add_type = QtWidgets.QPushButton(self.frame)
        self.btn_add_type.setGeometry(QtCore.QRect(340, 290, 93, 28))
        self.btn_add_type.setObjectName("btn_add_type")
        self.btn_add_sealing = QtWidgets.QPushButton(self.frame)
        self.btn_add_sealing.setGeometry(QtCore.QRect(500, 290, 93, 28))
        self.btn_add_sealing.setObjectName("btn_add_sealing")
        self.btn_add_running = QtWidgets.QPushButton(self.frame)
        self.btn_add_running.setGeometry(QtCore.QRect(660, 290, 93, 28))
        self.btn_add_running.setObjectName("btn_add_running")
        self.btn_add_concentrated = QtWidgets.QPushButton(self.frame)
        self.btn_add_concentrated.setGeometry(QtCore.QRect(820, 290, 93, 28))
        self.btn_add_concentrated.setObjectName("btn_add_concentrated")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1426, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_X.setText(_translate("MainWindow", "X"))
        self.label_Y.setText(_translate("MainWindow", "Y"))
        self.btn_add_point.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_render.setText(_translate("MainWindow", "Эпюр"))
        self.pushButton_graph_prod.setText(_translate("MainWindow", "График продольных"))
        self.pushButton_graph_norm.setText(_translate("MainWindow", "График нормальных"))
        self.pushButton_graph_peremesh.setText(_translate("MainWindow", "График перемещения"))
        self.pushButton_table_peremesh.setText(_translate("MainWindow", "Табл. перемещения"))
        self.pushButton_table_prod.setText(_translate("MainWindow", "Табл. продольных"))
        self.pushButton_table_norm.setText(_translate("MainWindow", "Табл. нормальных"))
        self.btn_add_kernel.setText(_translate("MainWindow", "Добавить"))
        self.btn_add_type.setText(_translate("MainWindow", "Добавить"))
        self.btn_add_sealing.setText(_translate("MainWindow", "Добавить"))
        self.btn_add_running.setText(_translate("MainWindow", "Добавить"))
        self.btn_add_concentrated.setText(_translate("MainWindow", "Добавить"))
        self.a = 2


    def add_function(self):
        self.btn_add_point.clicked.connect(self.add_point_form)
    
    def add_point_form(self):
        self.formLayout.setWidget(self.a, QtWidgets.QFormLayout.FieldRole, QtWidgets.QLabel("delhi"))
        self.a += 1
        #self.formLayout.addRow(QtWidgets.QLabel("city 1"), QtWidgets.QLabel("delhi"))
        print('asdasd')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
